namespace AimpSharp.Playlists.Enums
{
	public enum FlagsPlaylistReloadInfo
	{
		AIMP_PLAYLIST_RELOADINFO_FLAGS_DEFAULT = 0,
		AIMP_PLAYLIST_RELOADINFO_FLAGS_FULL = 1,
		AIMP_PLAYLIST_RELOADINFO_FLAGS_SELECTED = 2,
	}
}