namespace AimpSharp.Playlists.Enums
{
	public enum PropIdPlaylistItem
	{
		AIMP_PLAYLISTITEM_PROPID_CUSTOM = 0,
		AIMP_PLAYLISTITEM_PROPID_DISPLAYTEXT = 1,
		AIMP_PLAYLISTITEM_PROPID_FILEINFO = 2,
		AIMP_PLAYLISTITEM_PROPID_FILENAME = 3,
		AIMP_PLAYLISTITEM_PROPID_GROUP = 4,
		AIMP_PLAYLISTITEM_PROPID_INDEX = 5,
		AIMP_PLAYLISTITEM_PROPID_MARK = 6,
		AIMP_PLAYLISTITEM_PROPID_PLAYINGSWITCH = 7,
		AIMP_PLAYLISTITEM_PROPID_PLAYLIST = 8,
		AIMP_PLAYLISTITEM_PROPID_SELECTED = 9,
		AIMP_PLAYLISTITEM_PROPID_PLAYBACKQUEUEINDEX = 10,
	}
}