namespace AimpSharp.Menu
{
	public enum MenuId
	{
		AIMP_MENUID_COMMON_UTILITIES = 0,
		AIMP_MENUID_PLAYER_MAIN_FUNCTIONS = 10,
		AIMP_MENUID_PLAYER_MAIN_OPEN = 11,
		AIMP_MENUID_PLAYER_MAIN_OPTIONS = 12,
		AIMP_MENUID_PLAYER_PLAYLIST_ADDING = 20,
		AIMP_MENUID_PLAYER_PLAYLIST_DELETION = 21,
		AIMP_MENUID_PLAYER_PLAYLIST_SORTING = 22,
		AIMP_MENUID_PLAYER_PLAYLIST_MISCELLANEOUS = 23,
		AIMP_MENUID_PLAYER_PLAYLIST_MANAGE = 24,
		AIMP_MENUID_PLAYER_PLAYLIST_CONTEXT_ADDING = 30,
		AIMP_MENUID_PLAYER_PLAYLIST_CONTEXT_QUEUE = 31,
		AIMP_MENUID_PLAYER_PLAYLIST_CONTEXT_FUNCTIONS = 32,
		AIMP_MENUID_PLAYER_PLAYLIST_CONTEXT_SENDING = 33,
		AIMP_MENUID_PLAYER_PLAYLIST_CONTEXT_DELETION = 34,
		AIMP_MENUID_PLAYER_TRAY = 40,
		AIMP_MENUID_PLAYER_EQ_LIB = 41,
		AIMP_MENUID_PLAYER_STOP_OPTIONS = 42, // v4.00.1690
		AIMP_MENUID_ML_MISCELLANEOUS = 50, // v4.10
		AIMP_MENUID_ML_DELETION = 51, // v4.10
		AIMP_MENUID_ML_MAIN_DB = 60, // v4.10
		AIMP_MENUID_ML_MAIN_FUNCTIONS = 61, // v4.10
		AIMP_MENUID_ML_MAIN_OPEN = 62, // v4.10
		AIMP_MENUID_ML_MAIN_OPTIONS = 63, // v4.10
		AIMP_MENUID_ML_TABLE_CONTEXT_ADDING = 70, // v4.10
		AIMP_MENUID_ML_TABLE_CONTEXT_FUNCTIONS = 71, // v4.10
		AIMP_MENUID_ML_TABLE_CONTEXT_SENDING = 72, // v4.10
		AIMP_MENUID_ML_TABLE_CONTEXT_DELETION = 73, // v4.10
		AIMP_MENUID_ML_TREE_CONTEXT_FUNCTIONS = 80, // v4.10
		AIMP_MENUID_ML_TREE_CONTEXT_DELETION = 81, // v4.10
	}
}