namespace AimpSharp.Player.Enums
{
	public enum FlagsServicePlayer
	{
		AIMP_SERVICE_PLAYER_FLAGS_PLAY_FROM_PLAYLIST = 1,
		AIMP_SERVICE_PLAYER_FLAGS_PLAY_FROM_PLAYLIST_CAN_ADD = 2,
		AIMP_SERVICE_PLAYER_FLAGS_PLAY_WITHOUT_ADDING_TO_PLAYLIST = 4,
	}
}