namespace AimpSharp.Player.Enums
{
	public enum PropIdServicePlayer
	{

		AIMP_PLAYER_PROPID_STOP_AFTER_TRACK = 1,
		AIMP_PLAYER_PROPID_AUTO_JUMP_TO_NEXT_TRACK = 2,
		AIMP_PLAYER_PROPID_AUTOSWITCHING = 10,
		AIMP_PLAYER_PROPID_AUTOSWITCHING_CROSSFADE = 11, // msec
		AIMP_PLAYER_PROPID_AUTOSWITCHING_FADEIN = 12, // msec
		AIMP_PLAYER_PROPID_AUTOSWITCHING_FADEOUT = 13, // msec
		AIMP_PLAYER_PROPID_AUTOSWITCHING_PAUSE_BETWEEN_TRACKS = 14, // msec
		AIMP_PLAYER_PROPID_MANUALSWITCHING = 20,
		AIMP_PLAYER_PROPID_MANUALSWITCHING_CROSSFADE = 21, // msec
		AIMP_PLAYER_PROPID_MANUALSWITCHING_FADEIN = 22, // msec
		AIMP_PLAYER_PROPID_MANUALSWITCHING_FADEOUT = 23, // msec
	}
}