namespace AimpSharp.Menu.Enums
{
	public enum PropIdMenuItem
	{
		AIMP_MENUITEM_PROPID_CUSTOM = 0,
		AIMP_MENUITEM_PROPID_ACTION = 1,
		AIMP_MENUITEM_PROPID_ID = 2,
		AIMP_MENUITEM_PROPID_NAME = 3,
		AIMP_MENUITEM_PROPID_ENABLED = 4,
		AIMP_MENUITEM_PROPID_STYLE = 5, // One of the AIMP_MENUITEM_STYLE_XXX
		AIMP_MENUITEM_PROPID_EVENT = 6,
		AIMP_MENUITEM_PROPID_EVENT_ONSHOW = 7,
		AIMP_MENUITEM_PROPID_GLYPH = 10,
		AIMP_MENUITEM_PROPID_PARENT = 11,
		AIMP_MENUITEM_PROPID_VISIBLE = 12,
		AIMP_MENUITEM_PROPID_CHECKED = 13,
		AIMP_MENUITEM_PROPID_DEFAULT = 14,
		AIMP_MENUITEM_PROPID_SHORTCUT = 15,
	}
}