namespace AimpYouTubeDL.Api.Playlists.Enums
{
	public enum FlagsPlaylistAdd
	{
		AIMP_PLAYLIST_ADD_FLAGS_NOCHECKFORMAT = 1,
		AIMP_PLAYLIST_ADD_FLAGS_NOEXPAND = 2,
		AIMP_PLAYLIST_ADD_FLAGS_NOTHREADING = 4,
		AIMP_PLAYLIST_ADD_FLAGS_FILEINFO = 8,
	}
}