namespace AimpSharp.Playlists.Enums
{
	public enum FlagsPlaylistNotify
	{
		AIMP_PLAYLIST_NOTIFY_NAME = 1,
		AIMP_PLAYLIST_NOTIFY_SELECTION = 2,
		AIMP_PLAYLIST_NOTIFY_PLAYBACKCURSOR = 4,
		AIMP_PLAYLIST_NOTIFY_READONLY = 8,
		AIMP_PLAYLIST_NOTIFY_FOCUSINDEX = 16,
		AIMP_PLAYLIST_NOTIFY_CONTENT = 32,
		AIMP_PLAYLIST_NOTIFY_FILEINFO = 64,
		AIMP_PLAYLIST_NOTIFY_STATISTICS = 128,
		AIMP_PLAYLIST_NOTIFY_PLAYINGSWITCHS = 256,
		AIMP_PLAYLIST_NOTIFY_PREIMAGE = 512,
		AIMP_PLAYLIST_NOTIFY_MODIFIED = 1024,
		AIMP_PLAYLIST_NOTIFY_DEADSTATE = 2048,
		AIMP_PLAYLIST_NOTIFY_MAKEVISIBLE = 4096,
	}
}