namespace AimpYouTubeDL.Api.Playlists.Enums
{
	public enum FlagsPlaylistGetFiles
	{
		AIMP_PLAYLIST_GETFILES_FLAGS_SELECTED_ONLY = 0x1,
		AIMP_PLAYLIST_GETFILES_FLAGS_VISIBLE_ONLY = 0x2,
		AIMP_PLAYLIST_GETFILES_FLAGS_COLLAPSE_VIRTUAL = 0x4,
	}
}