namespace AimpYouTubeDL.Api.Playlists.Enums
{
	public enum FlagsPlaylistSortMode
	{
		AIMP_PLAYLIST_SORTMODE_TITLE = 1,
		AIMP_PLAYLIST_SORTMODE_FILENAME = 2,
		AIMP_PLAYLIST_SORTMODE_DURATION = 3,
		AIMP_PLAYLIST_SORTMODE_ARTIST = 4,
		AIMP_PLAYLIST_SORTMODE_INVERSE = 5,
		AIMP_PLAYLIST_SORTMODE_RANDOMIZE = 6,
	}
}