namespace AimpSharp.Playlists.Enums
{
	public enum PropIdPlaylist
	{
		AIMP_PLAYLIST_PROPID_NAME = 1,
		AIMP_PLAYLIST_PROPID_READONLY = 2,
		AIMP_PLAYLIST_PROPID_FOCUSED_OBJECT = 3,
		AIMP_PLAYLIST_PROPID_ID = 4,
		AIMP_PLAYLIST_PROPID_GROUPPING = 10,
		AIMP_PLAYLIST_PROPID_GROUPPING_OVERRIDEN = 11,
		AIMP_PLAYLIST_PROPID_GROUPPING_TEMPLATE = 12,
		AIMP_PLAYLIST_PROPID_GROUPPING_AUTOMERGING = 13,
		AIMP_PLAYLIST_PROPID_FORMATING_OVERRIDEN = 20,
		AIMP_PLAYLIST_PROPID_FORMATING_LINE1_TEMPLATE = 21,
		AIMP_PLAYLIST_PROPID_FORMATING_LINE2_TEMPLATE = 22,
		AIMP_PLAYLIST_PROPID_VIEW_OVERRIDEN = 30,
		AIMP_PLAYLIST_PROPID_VIEW_DURATION = 31,
		AIMP_PLAYLIST_PROPID_VIEW_EXPAND_BUTTONS = 32,
		AIMP_PLAYLIST_PROPID_VIEW_MARKS = 33,
		AIMP_PLAYLIST_PROPID_VIEW_NUMBERS = 34,
		AIMP_PLAYLIST_PROPID_VIEW_NUMBERS_ABSOLUTE = 35,
		AIMP_PLAYLIST_PROPID_VIEW_SECOND_LINE = 36,
		AIMP_PLAYLIST_PROPID_VIEW_SWITCHES = 37,
		AIMP_PLAYLIST_PROPID_FOCUSINDEX = 50,
		AIMP_PLAYLIST_PROPID_PLAYBACKCURSOR = 51,
		AIMP_PLAYLIST_PROPID_PLAYINGINDEX = 52,
		AIMP_PLAYLIST_PROPID_SIZE = 53,
		AIMP_PLAYLIST_PROPID_DURATION = 54,
		AIMP_PLAYLIST_PROPID_PREIMAGE = 60,
	}
}