namespace AimpYouTubeDL.Api.Playlists.Enums
{
	public enum PropIdPlaylistPreimage
	{
		AIMP_PLAYLISTPREIMAGE_PROPID_FACTORYID = 1,
		AIMP_PLAYLISTPREIMAGE_PROPID_AUTOSYNC = 2,
		AIMP_PLAYLISTPREIMAGE_PROPID_HASDIALOG = 3,
		AIMP_PLAYLISTPREIMAGE_PROPID_SORTTEMPLATE = 4,
		AIMP_PLAYLISTPREIMAGE_PROPID_AUTOSYNC_ON_STARTUP = 5,
	}
}