namespace AimpYouTubeDL.Api.Playlists.Enums
{
	public enum PropIdPlaylistGroup
	{
		AIMP_PLAYLISTGROUP_PROPID_NAME = 1,
		AIMP_PLAYLISTGROUP_PROPID_EXPANDED = 2,
		AIMP_PLAYLISTGROUP_PROPID_DURATION = 3,
		AIMP_PLAYLISTGROUP_PROPID_INDEX = 4,
		AIMP_PLAYLISTGROUP_PROPID_SELECTED = 5,
	}
}