namespace AimpYouTubeDL.Api.Plugins.Enums
{
	public enum PluginCategory
	{
		AIMP_PLUGIN_CATEGORY_ADDONS = 0x1,
		AIMP_PLUGIN_CATEGORY_DECODERS = 0x2,
		AIMP_PLUGIN_CATEGORY_VISUALS = 0x4,
		AIMP_PLUGIN_CATEGORY_DSP = 0x8,
	}
}