namespace AimpSharp.Core.Enums
{
	public enum CorePath
	{
		AIMP_CORE_PATH_PROFILE = 0,
		AIMP_CORE_PATH_PLAYLISTS = 1,
		AIMP_CORE_PATH_LANGS = 2,
		AIMP_CORE_PATH_SKINS = 3,
		AIMP_CORE_PATH_PLUGINS = 4,
		AIMP_CORE_PATH_ICONS = 5,
		AIMP_CORE_PATH_AUDIOLIBRARY = 6,
		AIMP_CORE_PATH_ENCODERS = 8,
		AIMP_CORE_PATH_HELP = 9,
		AIMP_CORE_PATH_SKINS_COMMON = 11,
	}
}