namespace AimpYouTubeDL.Api.Core.Enums
{
	public enum ServiceVersionState
	{
		AIMP_SERVICE_VERSION_STATE_RELEASE = 0,
		AIMP_SERVICE_VERSION_STATE_RELEASE_CANDIDATE = 1,
		AIMP_SERVICE_VERSION_STATE_BETA = 2,
		AIMP_SERVICE_VERSION_STATE_ALPHA = 3,
	}
}