namespace AimpSharp.Actions.Enums
{
	public enum ActionPropId
	{
		AIMP_ACTION_PROPID_CUSTOM = 0,
		AIMP_ACTION_PROPID_ID = 1,
		AIMP_ACTION_PROPID_NAME = 2,
		AIMP_ACTION_PROPID_GROUPNAME = 3,
		AIMP_ACTION_PROPID_ENABLED = 4,
		AIMP_ACTION_PROPID_DEFAULTLOCALHOTKEY = 5,
		AIMP_ACTION_PROPID_DEFAULTGLOBALHOTKEY = 6,
		AIMP_ACTION_PROPID_DEFAULTGLOBALHOTKEY2 = 7,
		AIMP_ACTION_PROPID_EVENT = 8,
	}
}