namespace AimpSharp.AlbumArt.Enums
{
	public enum FlagsAlbumArt
	{
		AIMP_SERVICE_ALBUMART_FLAGS_NOCACHE = 1,
		AIMP_SERVICE_ALBUMART_FLAGS_ORIGINAL = 2,
		AIMP_SERVICE_ALBUMART_FLAGS_WAITFOR = 4,
		AIMP_SERVICE_ALBUMART_FLAGS_OFFLINE = 8,
	}
}