namespace AimpSharp.AlbumArt.Enums
{
	public enum AlbumArtCategory
	{
		AIMP_ALBUMART_PROVIDER_CATEGORY_TAGS = 0,
		AIMP_ALBUMART_PROVIDER_CATEGORY_FILE = 1,
		AIMP_ALBUMART_PROVIDER_CATEGORY_INTERNET = 2,
		AIMP_ALBUMART_PROVIDER_CATEGORY_MASK = 0xF,
	}
}