namespace AimpSharp.AlbumArt.Enums
{
	public enum PropIdAlbumArt
	{
		AIMP_SERVICE_ALBUMART_PROPID_FIND_IN_FILES = 1,
		AIMP_SERVICE_ALBUMART_PROPID_FIND_IN_FILES_MASKS = 2,
		AIMP_SERVICE_ALBUMART_PROPID_FIND_IN_FILES_EXTS = 3,
		AIMP_SERVICE_ALBUMART_PROPID_FIND_IN_INTERNET = 4,
		AIMP_SERVICE_ALBUMART_PROPID_FIND_IN_INTERNET_MAX_FILE_SIZE = 5,
	}
}