namespace AimpYouTubeDL.Api.Player.Enums
{
	public enum FlagsPlaybackQueue
	{
		AIMP_PLAYBACKQUEUE_FLAGS_START_FROM_BEGINNING = 1,
		AIMP_PLAYBACKQUEUE_FLAGS_START_FROM_CURSOR = 2,
		AIMP_PLAYBACKQUEUE_FLAGS_START_FROM_ITEM = 3,
	}
}