namespace AimpSharp.Objects
{
	public enum ImageDraw
	{
		AIMP_IMAGE_DRAW_STRETCHMODE_STRETCH = 0,
		AIMP_IMAGE_DRAW_QUALITY_DEFAULT = 0,
		AIMP_IMAGE_DRAW_STRETCHMODE_FILL = 1,
		AIMP_IMAGE_DRAW_STRETCHMODE_FIT = 2,
		AIMP_IMAGE_DRAW_STRETCHMODE_TILE = 4,
		AIMP_IMAGE_DRAW_QUALITY_LOW = 8,
		AIMP_IMAGE_DRAW_QUALITY_HIGH = 16,
	}
}