namespace AimpSharp.Objects
{
	public enum StringCase
	{
		AIMP_STRING_CASE_LOWER = 1,
		AIMP_STRING_CASE_UPPER = 2,
		AIMP_STRING_CASE_ALL_WORDS_WITH_CAPICAL_LETTER = 3,
		AIMP_STRING_CASE_FIRST_WORD_WITH_CAPICAL_LETTER = 4,
	}
}