namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum FlagsBorderStyle
	{
		AIMPUI_FLAGS_BORDERSTYLE_SIZEABLE = 0,
		AIMPUI_FLAGS_BORDERSTYLE_SINGLE = 1,
		AIMPUI_FLAGS_BORDERSTYLE_DIALOG = 2,
		AIMPUI_FLAGS_BORDERSTYLE_TOOLWINDOW = 3,
		AIMPUI_FLAGS_BORDERSTYLE_TOOLWINDOWSIZABLE = 4,
		AIMPUI_FLAGS_BORDERSTYLE_NONE = 5,
	}
}