namespace AimpSharp.GUI.Enums
{
	public enum PropIdWinControl
	{
		AIMPUI_WINCONTROL_PROPID_FOCUSED = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 1,
		AIMPUI_WINCONTROL_PROPID_TABORDER = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 2,
		AIMPUI_WINCONTROL_MAX_PROPID = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 10,
	}
}