namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdTabSheet
	{
		AIMPUI_TABSHEET_PROPID_CAPTION = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_TABSHEET_PROPID_INDEX = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_TABSHEET_PROPID_VISIBLE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
	}
}