namespace AimpSharp.GUI.Enums
{
	public enum PropIdLabel
	{
		AIMPUI_LABEL_PROPID_AUTOSIZE = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 1,
		AIMPUI_LABEL_PROPID_LINE = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 2,
		AIMPUI_LABEL_PROPID_TEXT = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 3,
		AIMPUI_LABEL_PROPID_TEXTALIGN = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 4,
		AIMPUI_LABEL_PROPID_TEXTALIGNVERT = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 5,
		AIMPUI_LABEL_PROPID_TEXTCOLOR = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 6,
		AIMPUI_LABEL_PROPID_TEXTSTYLE = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 7,
		AIMPUI_LABEL_PROPID_TRANSPARENT = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 8,
		AIMPUI_LABEL_PROPID_URL = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 9,
		AIMPUI_LABEL_PROPID_WORDWRAP = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 10,
		AIMPUI_LABEL_MAX_PROPID = PropIdControl.AIMPUI_CONTROL_MAX_PROPID + 20,
	}
}