namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdImage
	{
		AIMPUI_IMAGE_PROPID_IMAGE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_IMAGE_PROPID_IMAGESTRETCHMODE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_IMAGE_PROPID_IMAGEINDEX = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_IMAGE_PROPID_IMAGELIST = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}