namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdProgressDialog
	{
		AIMPUI_PROGRESSDLG_PROPID_CAPTION = 1,
		AIMPUI_PROGRESSDLG_PROPID_MESSAGE = 2,
		AIMPUI_PROGRESSDLG_PROPID_SHOW_PROGRESS_ON_TASKBAR = 3,
	}
}