namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdTreeListGroup
	{
		AIMPUI_TL_GROUP_PROPID_CAPTION = 1,
		AIMPUI_TL_GROUP_PROPID_CHECKSTATE = 2,
		AIMPUI_TL_GROUP_PROPID_EXPANDED = 3,
		AIMPUI_TL_GROUP_PROPID_INDEX = 4,
		AIMPUI_TL_GROUP_PROPID_SELECTED = 5,
	}
}