namespace AimpSharp.GUI.Enums
{
	public enum PropIdSplitter
	{
		AIMPUI_SPLITTER_PROPID_CANHIDE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_SPLITTER_PROPID_CONTROL = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
	}
}