namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdEditButton
	{
		AIMPUI_EDITBUTTON_PROPID_CUSTOM = 0,
		AIMPUI_EDITBUTTON_PROPID_CAPTION = 1,
		AIMPUI_EDITBUTTON_PROPID_ENABLED = 2,
		AIMPUI_EDITBUTTON_PROPID_HINT = 3,
		AIMPUI_EDITBUTTON_PROPID_INDEX = 4,
		AIMPUI_EDITBUTTON_PROPID_IMAGEINDEX = 5,
		AIMPUI_EDITBUTTON_PROPID_VISIBLE = 6,
		AIMPUI_EDITBUTTON_PROPID_WIDTH = 7,
	}
}