namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdSlider
	{
		AIMPUI_SLIDER_PROPID_HORIZONTAL = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_SLIDER_PROPID_MARKS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_SLIDER_PROPID_PAGESIZE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_SLIDER_PROPID_TRANSPARENT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_SLIDER_PROPID_VALUE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_SLIDER_PROPID_VALUEDEFAULT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_SLIDER_PROPID_VALUEMAX = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_SLIDER_PROPID_VALUEMIN = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
	}
}