namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdCheckBox
	{
		AIMPUI_CHECKBOX_PROPID_AUTOSIZE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_CHECKBOX_PROPID_CAPTION = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_CHECKBOX_PROPID_STATE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_CHECKBOX_PROPID_WORDWRAP = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}