namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdButton
	{
		AIMPUI_BUTTON_PROPID_CAPTION = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_BUTTON_PROPID_FOCUSONCLICK = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_BUTTON_PROPID_DEFAULT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_BUTTON_PROPID_DROPDOWNMENU = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_BUTTON_PROPID_IMAGEINDEX = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_BUTTON_PROPID_IMAGELIST = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_BUTTON_PROPID_MODALRESULT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_BUTTON_PROPID_STYLE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
	}
}