namespace AimpSharp.GUI.Enums
{
	public enum PropIdBaseEdit
	{
		AIMPUI_BASEEDIT_PROPID_BORDERS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_BASEEDIT_PROPID_MAXLENGTH = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_BASEEDIT_PROPID_READONLY = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_BASEEDIT_PROPID_SELLENGTH = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_BASEEDIT_PROPID_SELSTART = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_BASEEDIT_PROPID_SELTEXT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_BASEEDIT_PROPID_TEXT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_BASEEDIT_MAX_PROPID = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 10,
	}
}