namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdForm
	{
		AIMPUI_FORM_PROPID_BORDERICONS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_FORM_PROPID_BORDERSTYLE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_FORM_PROPID_CAPTION = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_FORM_PROPID_CLOSEBYESCAPE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_FORM_PROPID_ICON = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_FORM_PROPID_PADDING = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_FORM_PROPID_SHOWONTASKBAR = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_FORM_PROPID_STYLE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
	}
}