namespace AimpSharp.GUI.Enums
{
	public enum PropIdSpinEdit
	{
		AIMPUI_SPINEDIT_PROPID_DISPLAYMASK = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_SPINEDIT_PROPID_INCREMENT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_SPINEDIT_PROPID_MAXVALUE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_SPINEDIT_PROPID_MINVALUE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_SPINEDIT_PROPID_VALUE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_SPINEDIT_PROPID_VALUETYPE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
	}
}