namespace AimpSharp.GUI.Enums
{
	public enum PropIdComboBox
	{
		AIMPUI_COMBOBOX_PROPID_AUTOCOMPLETE = PropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 1,
		AIMPUI_COMBOBOX_PROPID_ITEMINDEX = PropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 2,
		AIMPUI_COMBOBOX_PROPID_ITEMOBJECT = PropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 3,
		AIMPUI_COMBOBOX_PROPID_TEXT = PropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 4,
		AIMPUI_COMBOBOX_PROPID_STYLE = PropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 5,
	}
}