namespace AimpSharp.GUI.Enums
{
	public enum PropIdTreeList
	{
		AIMPUI_TL_PROPID_ALLOW_DELETING = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_TL_PROPID_ALLOW_EDITING = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_TL_PROPID_ALLOW_FOCUS_CELLS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_TL_PROPID_ALLOW_MULTISELECT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_TL_PROPID_ALLOW_REORDER_COLUMNS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_TL_PROPID_ALLOW_SHOWWHIDE_COLUMNS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_TL_PROPID_AUTOCHECK_SUBNODES = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_TL_PROPID_BORDERS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
		AIMPUI_TL_PROPID_CELL_HINTS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 9,
		AIMPUI_TL_PROPID_CHECKBOXES = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 10,
		AIMPUI_TL_PROPID_COLUMN_AUTOWIDTH = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 11,
		AIMPUI_TL_PROPID_COLUMN_HEIGHT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 12,
		AIMPUI_TL_PROPID_COLUMN_IMAGES = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 13,
		AIMPUI_TL_PROPID_COLUMN_VISIBLE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 14,
		AIMPUI_TL_PROPID_DRAG_SORTING = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 15,
		AIMPUI_TL_PROPID_DRAG_SORTING_CHANGE_LEVEL = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 16,
		AIMPUI_TL_PROPID_GRID_LINES = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 20,
		AIMPUI_TL_PROPID_GROUP_HEIGHT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 21,
		AIMPUI_TL_PROPID_GROUPS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 22,
		AIMPUI_TL_PROPID_GROUPS_ALLOW_COLLAPSE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 23,
		AIMPUI_TL_PROPID_GROUPS_FOCUS_ON_CLICK = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 24,
		AIMPUI_TL_PROPID_HOT_TRACK = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 25,
		AIMPUI_TL_PROPID_INCSEARCH_COLUMN_INDEX = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 26,
		AIMPUI_TL_PROPID_NODE_HEIGHT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 27,
		AIMPUI_TL_PROPID_NODE_IMAGE_ALIGNMENT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 28,
		AIMPUI_TL_PROPID_NODE_IMAGES = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 29,
		AIMPUI_TL_PROPID_SORTING_MODE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 30,
	}
}