namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdCategory
	{
		AIMPUI_CATEGORY_PROPID_AUTOSIZE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_CATEGORY_PROPID_CAPTION = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
	}
}