namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdControl
	{
		AIMPUI_CONTROL_PROPID_CUSTOM = 0,
		AIMPUI_CONTROL_PROPID_ENABLED = 1,
		AIMPUI_CONTROL_PROPID_HINT = 2,
		AIMPUI_CONTROL_PROPID_NAME = 3,
		AIMPUI_CONTROL_PROPID_PARENT = 4,
		AIMPUI_CONTROL_PROPID_POPUPMENU = 5,
		AIMPUI_CONTROL_PROPID_VISIBLE = 6,
		AIMPUI_CONTROL_MAX_PROPID = 20,
	}
}