namespace AimpYouTubeDL.Api.GUI.Enums
{
	public enum PropIdBaseButtonnedEdit
	{
		AIMPUI_BUTTONEDEDIT_PROPID_BUTTONSIMAGES = PropIdBaseEdit.AIMPUI_BASEEDIT_MAX_PROPID + 1,
		AIMPUI_BUTTONEDEDIT_MAX_PROPID = PropIdBaseEdit.AIMPUI_BASEEDIT_MAX_PROPID + 10,
	}
}