namespace AimpYouTubeDL.Api.FileManager.Enums
{
	public enum FlagsFileStreaming
	{
		AIMP_SERVICE_FILESTREAMING_FLAG_CREATENEW = 1,
		AIMP_SERVICE_FILESTREAMING_FLAG_READWRITE = 2,
		AIMP_SERVICE_FILESTREAMING_FLAG_MAPTOMEMORY = 4,
	}
}