namespace AimpYouTubeDL.Api.FileManager.Enums
{
	public enum PropIdVirtualFile
	{
		AIMP_VIRTUALFILE_PROPID_FILEURI = 0,
		AIMP_VIRTUALFILE_PROPID_AUDIOSOURCEFILE = 1,
		AIMP_VIRTUALFILE_PROPID_CLIPSTART = 2,
		AIMP_VIRTUALFILE_PROPID_CLIPFINISH = 3,
		AIMP_VIRTUALFILE_PROPID_INDEXINSET = 4,
		AIMP_VIRTUALFILE_PROPID_FILEFORMAT = 5,
	}
}