namespace AimpYouTubeDL.Api.FileManager.Enums
{
	public enum PropIdFileInfo
	{
		AIMP_FILEINFO_PROPID_CUSTOM = 0, // IUnknown
		AIMP_FILEINFO_PROPID_ALBUM = 1, // IAIMPString
		AIMP_FILEINFO_PROPID_ALBUMART = 2, // IAIMPImage / IAIMPImageContainer
		AIMP_FILEINFO_PROPID_ALBUMARTIST = 3, // IAIMPString
		AIMP_FILEINFO_PROPID_ALBUMGAIN = 4, // Float
		AIMP_FILEINFO_PROPID_ALBUMPEAK = 5, // Float
		AIMP_FILEINFO_PROPID_ARTIST = 6, // IAIMPString
		AIMP_FILEINFO_PROPID_BITRATE = 7, // Int32
		AIMP_FILEINFO_PROPID_BPM = 8, // Int32
		AIMP_FILEINFO_PROPID_CHANNELS = 9, // Int32
		AIMP_FILEINFO_PROPID_COMMENT = 10, // IAIMPString
		AIMP_FILEINFO_PROPID_COMPOSER = 11, // IAIMPString
		AIMP_FILEINFO_PROPID_COPYRIGHT = 12, // IAIMPString
		AIMP_FILEINFO_PROPID_CUESHEET = 13, // IAIMPString
		AIMP_FILEINFO_PROPID_DATE = 14, // IAIMPString
		AIMP_FILEINFO_PROPID_DISKNUMBER = 15, // IAIMPString
		AIMP_FILEINFO_PROPID_DISKTOTAL = 16, // IAIMPString
		AIMP_FILEINFO_PROPID_DURATION = 17, // Float
		AIMP_FILEINFO_PROPID_FILENAME = 18, // IAIMPString
		AIMP_FILEINFO_PROPID_FILESIZE = 19, // Int64
		AIMP_FILEINFO_PROPID_GENRE = 20, // IAIMPString
		AIMP_FILEINFO_PROPID_LYRICS = 21, // IAIMPString
		AIMP_FILEINFO_PROPID_PUBLISHER = 23, // Int32
		AIMP_FILEINFO_PROPID_SAMPLERATE = 24, // Int32
		AIMP_FILEINFO_PROPID_TITLE = 25, // IAIMPString
		AIMP_FILEINFO_PROPID_TRACKGAIN = 26, // Float
		AIMP_FILEINFO_PROPID_TRACKNUMBER = 27, // IAIMPString
		AIMP_FILEINFO_PROPID_TRACKPEAK = 28, // Float
		AIMP_FILEINFO_PROPID_TRACKTOTAL = 29, // IAIMPString
		AIMP_FILEINFO_PROPID_URL = 30, // IAIMPString
		AIMP_FILEINFO_PROPID_BITDEPTH = 31, // Int32
		AIMP_FILEINFO_PROPID_CODEC = 32, // IAIMPString
		AIMP_FILEINFO_PROPID_CONDUCTOR = 33, // IAIMPString
		AIMP_FILEINFO_PROPID_MOOD = 34, // IAIMPString
		AIMP_FILEINFO_PROPID_CATALOG = 35, // IAIMPString
		AIMP_FILEINFO_PROPID_ISRC = 36, // IAIMPString
		AIMP_FILEINFO_PROPID_LYRICIST = 37, // IAIMPString
		AIMP_FILEINFO_PROPID_ENCODEDBY = 38, // IAIMPString
		AIMP_FILEINFO_PROPID_RATING = 39, // Int32
		AIMP_FILEINFO_PROPID_STAT_ADDINGDATE = 40, // Float (TDateTime)
		AIMP_FILEINFO_PROPID_STAT_LASTPLAYDATE = 41, // Float (TDateTime)
		AIMP_FILEINFO_PROPID_STAT_MARK = 42, // Int32
		AIMP_FILEINFO_PROPID_STAT_PLAYCOUNT = 43, // Int32
		AIMP_FILEINFO_PROPID_STAT_RATING = 44, // Float
		AIMP_FILEINFO_PROPID_STAT_DISPLAYING_MARK = 22, // Float
	}
}