namespace AimpSharp.GUI.Enums
{
	public enum PropIdPanel
	{
		AIMPUI_PANEL_PROPID_AUTOSIZE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_PANEL_PROPID_BORDERS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_PANEL_PROPID_TRANSPARENT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_PANEL_PROPID_PADDING = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}