namespace AimpSharp.GUI.Enums
{
	public enum PropIdProgressBar
	{
		AIMPUI_PROGRESSBAR_PROPID_INDETERMINATE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_PROGRESSBAR_PROPID_MAX = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_PROGRESSBAR_PROPID_MIN = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_PROGRESSBAR_PROPID_PROGRESS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}