namespace AimpSharp.GUI.Enums
{
	public enum PropIdTreeListColumn
	{
		AIMPUI_TL_COLUMN_PROPID_CAN_RESIZE = 1,
		AIMPUI_TL_COLUMN_PROPID_CAPTION = 2,
		AIMPUI_TL_COLUMN_PROPID_DRAWINDEX = 3,
		AIMPUI_TL_COLUMN_PROPID_IMAGEINDEX = 4,
		AIMPUI_TL_COLUMN_PROPID_INDEX = 5,
		AIMPUI_TL_COLUMN_PROPID_TEXT_ALIGNMENT = 6,
		AIMPUI_TL_COLUMN_PROPID_TEXT_VISIBLE = 7,
		AIMPUI_TL_COLUMN_PROPID_VISIBLE = 8,
		AIMPUI_TL_COLUMN_PROPID_WIDTH = 9,
	}
}