namespace AimpSharp.GUI.Enums
{
	public enum PropIdGroupBox
	{
		AIMPUI_GROUPBOX_PROPID_AUTOSIZE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_GROUPBOX_PROPID_BORDERS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_GROUPBOX_PROPID_TRANSPARENT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_GROUPBOX_PROPID_CHECKMODE = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_GROUPBOX_PROPID_CHECKED = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_GROUPBOX_PROPID_CAPTION = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
	}
}