namespace AimpSharp.GUI.Enums
{
	public enum PropIdBBCBox
	{
		AIMPUI_BBCBOX_PROPID_BORDERS = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_BBCBOX_PROPID_TEXT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_BBCBOX_PROPID_TRANSPARENT = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_BBCBOX_PROPID_WORDWRAP = PropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}