namespace AimpSharp.GUI.Enums
{
	public enum UiFlagsModalResult
	{
		AIMPUI_FLAGS_MODALRESULT_NONE = 0,
		AIMPUI_FLAGS_MODALRESULT_OK = 1,
		AIMPUI_FLAGS_MODALRESULT_CANCEL = 2,
		AIMPUI_FLAGS_MODALRESULT_ABORT = 3,
		AIMPUI_FLAGS_MODALRESULT_RETRY = 4,
		AIMPUI_FLAGS_MODALRESULT_IGNORE = 5,
		AIMPUI_FLAGS_MODALRESULT_YES = 6,
		AIMPUI_FLAGS_MODALRESULT_NO = 7,
		AIMPUI_FLAGS_MODALRESULT_CLOSE = 8,
		AIMPUI_FLAGS_MODALRESULT_HELP = 9,
		AIMPUI_FLAGS_MODALRESULT_TRYAGAIN = 10,
		AIMPUI_FLAGS_MODALRESULT_CONTINUE = 11,
	}
}