namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdWinControl
	{
		AIMPUI_WINCONTROL_PROPID_FOCUSED = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 1,
		AIMPUI_WINCONTROL_PROPID_TABORDER = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 2,
		AIMPUI_WINCONTROL_MAX_PROPID = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 10,
	}
}