namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdButton
	{
		AIMPUI_BUTTON_PROPID_CAPTION = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_BUTTON_PROPID_FOCUSONCLICK = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_BUTTON_PROPID_DEFAULT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_BUTTON_PROPID_DROPDOWNMENU = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_BUTTON_PROPID_IMAGEINDEX = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_BUTTON_PROPID_IMAGELIST = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_BUTTON_PROPID_MODALRESULT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_BUTTON_PROPID_STYLE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
	}
}