namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdTabSheet
	{
		AIMPUI_TABSHEET_PROPID_CAPTION = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_TABSHEET_PROPID_INDEX = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_TABSHEET_PROPID_VISIBLE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
	}
}