namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdGroupBox
	{
		AIMPUI_GROUPBOX_PROPID_AUTOSIZE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_GROUPBOX_PROPID_BORDERS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_GROUPBOX_PROPID_TRANSPARENT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_GROUPBOX_PROPID_CHECKMODE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_GROUPBOX_PROPID_CHECKED = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_GROUPBOX_PROPID_CAPTION = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
	}
}