namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdImage
	{
		AIMPUI_IMAGE_PROPID_IMAGE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_IMAGE_PROPID_IMAGESTRETCHMODE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_IMAGE_PROPID_IMAGEINDEX = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_IMAGE_PROPID_IMAGELIST = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}