namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdSpinEdit
	{
		AIMPUI_SPINEDIT_PROPID_DISPLAYMASK = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_SPINEDIT_PROPID_INCREMENT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_SPINEDIT_PROPID_MAXVALUE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_SPINEDIT_PROPID_MINVALUE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_SPINEDIT_PROPID_VALUE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_SPINEDIT_PROPID_VALUETYPE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
	}
}