namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdCheckBox
	{
		AIMPUI_CHECKBOX_PROPID_AUTOSIZE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_CHECKBOX_PROPID_CAPTION = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_CHECKBOX_PROPID_STATE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_CHECKBOX_PROPID_WORDWRAP = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}