namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdProgressBar
	{
		AIMPUI_PROGRESSBAR_PROPID_INDETERMINATE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_PROGRESSBAR_PROPID_MAX = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_PROGRESSBAR_PROPID_MIN = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_PROGRESSBAR_PROPID_PROGRESS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}