namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdPanel
	{
		AIMPUI_PANEL_PROPID_AUTOSIZE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_PANEL_PROPID_BORDERS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_PANEL_PROPID_TRANSPARENT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_PANEL_PROPID_PADDING = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}