namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdBBCBox
	{
		AIMPUI_BBCBOX_PROPID_BORDERS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_BBCBOX_PROPID_TEXT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_BBCBOX_PROPID_TRANSPARENT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_BBCBOX_PROPID_WORDWRAP = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
	}
}