namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdComboBox
	{
		AIMPUI_COMBOBOX_PROPID_AUTOCOMPLETE = UiPropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 1,
		AIMPUI_COMBOBOX_PROPID_ITEMINDEX = UiPropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 2,
		AIMPUI_COMBOBOX_PROPID_ITEMOBJECT = UiPropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 3,
		AIMPUI_COMBOBOX_PROPID_TEXT = UiPropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 4,
		AIMPUI_COMBOBOX_PROPID_STYLE = UiPropIdBaseButtonnedEdit.AIMPUI_BUTTONEDEDIT_MAX_PROPID + 5,
	}
}