namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdLabel
	{
		AIMPUI_LABEL_PROPID_AUTOSIZE = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 1,
		AIMPUI_LABEL_PROPID_LINE = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 2,
		AIMPUI_LABEL_PROPID_TEXT = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 3,
		AIMPUI_LABEL_PROPID_TEXTALIGN = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 4,
		AIMPUI_LABEL_PROPID_TEXTALIGNVERT = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 5,
		AIMPUI_LABEL_PROPID_TEXTCOLOR = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 6,
		AIMPUI_LABEL_PROPID_TEXTSTYLE = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 7,
		AIMPUI_LABEL_PROPID_TRANSPARENT = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 8,
		AIMPUI_LABEL_PROPID_URL = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 9,
		AIMPUI_LABEL_PROPID_WORDWRAP = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 10,
		AIMPUI_LABEL_MAX_PROPID = UiPropIdControl.AIMPUI_CONTROL_MAX_PROPID + 20,
	}
}