namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdTreeListNode
	{
		AIMPUI_TL_NODE_PROPID_ABS_VISIBLE_INDEX = 0,
		AIMPUI_TL_NODE_PROPID_CHECK_ENABLED = 1,
		AIMPUI_TL_NODE_PROPID_CHECKED = 2,
		AIMPUI_TL_NODE_PROPID_CHILDREN_CHECK_STATE = 3,
		AIMPUI_TL_NODE_PROPID_EXPANDED = 4,
		AIMPUI_TL_NODE_PROPID_IMAGEINDEX = 5,
		AIMPUI_TL_NODE_PROPID_INDEX = 6,
		AIMPUI_TL_NODE_PROPID_LEVEL = 7,
		AIMPUI_TL_NODE_PROPID_SELECTED = 8,
		AIMPUI_TL_NODE_PROPID_TAG = 9,
	}
}