namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdTreeList
	{
		AIMPUI_TL_PROPID_ALLOW_DELETING = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_TL_PROPID_ALLOW_EDITING = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_TL_PROPID_ALLOW_FOCUS_CELLS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_TL_PROPID_ALLOW_MULTISELECT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_TL_PROPID_ALLOW_REORDER_COLUMNS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_TL_PROPID_ALLOW_SHOWWHIDE_COLUMNS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_TL_PROPID_AUTOCHECK_SUBNODES = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_TL_PROPID_BORDERS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
		AIMPUI_TL_PROPID_CELL_HINTS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 9,
		AIMPUI_TL_PROPID_CHECKBOXES = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 10,
		AIMPUI_TL_PROPID_COLUMN_AUTOWIDTH = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 11,
		AIMPUI_TL_PROPID_COLUMN_HEIGHT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 12,
		AIMPUI_TL_PROPID_COLUMN_IMAGES = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 13,
		AIMPUI_TL_PROPID_COLUMN_VISIBLE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 14,
		AIMPUI_TL_PROPID_DRAG_SORTING = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 15,
		AIMPUI_TL_PROPID_DRAG_SORTING_CHANGE_LEVEL = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 16,
		AIMPUI_TL_PROPID_GRID_LINES = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 20,
		AIMPUI_TL_PROPID_GROUP_HEIGHT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 21,
		AIMPUI_TL_PROPID_GROUPS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 22,
		AIMPUI_TL_PROPID_GROUPS_ALLOW_COLLAPSE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 23,
		AIMPUI_TL_PROPID_GROUPS_FOCUS_ON_CLICK = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 24,
		AIMPUI_TL_PROPID_HOT_TRACK = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 25,
		AIMPUI_TL_PROPID_INCSEARCH_COLUMN_INDEX = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 26,
		AIMPUI_TL_PROPID_NODE_HEIGHT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 27,
		AIMPUI_TL_PROPID_NODE_IMAGE_ALIGNMENT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 28,
		AIMPUI_TL_PROPID_NODE_IMAGES = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 29,
		AIMPUI_TL_PROPID_SORTING_MODE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 30,
	}
}