namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdSlider
	{
		AIMPUI_SLIDER_PROPID_HORIZONTAL = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_SLIDER_PROPID_MARKS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_SLIDER_PROPID_PAGESIZE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_SLIDER_PROPID_TRANSPARENT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_SLIDER_PROPID_VALUE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_SLIDER_PROPID_VALUEDEFAULT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_SLIDER_PROPID_VALUEMAX = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_SLIDER_PROPID_VALUEMIN = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
	}
}