namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdForm
	{
		AIMPUI_FORM_PROPID_BORDERICONS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_FORM_PROPID_BORDERSTYLE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_FORM_PROPID_CAPTION = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_FORM_PROPID_CLOSEBYESCAPE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_FORM_PROPID_ICON = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_FORM_PROPID_PADDING = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_FORM_PROPID_SHOWONTASKBAR = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_FORM_PROPID_STYLE = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 8,
	}
}