namespace AimpSharp.GUI.Enums
{
	public enum UiPropIdBaseEdit
	{
		AIMPUI_BASEEDIT_PROPID_BORDERS = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 1,
		AIMPUI_BASEEDIT_PROPID_MAXLENGTH = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 2,
		AIMPUI_BASEEDIT_PROPID_READONLY = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 3,
		AIMPUI_BASEEDIT_PROPID_SELLENGTH = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 4,
		AIMPUI_BASEEDIT_PROPID_SELSTART = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 5,
		AIMPUI_BASEEDIT_PROPID_SELTEXT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 6,
		AIMPUI_BASEEDIT_PROPID_TEXT = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 7,
		AIMPUI_BASEEDIT_MAX_PROPID = UiPropIdWinControl.AIMPUI_WINCONTROL_MAX_PROPID + 10,
	}
}