namespace AimpYouTubeDL.Api.Options
{
	public enum NotificationOptionsDialog
	{
		AIMP_SERVICE_OPTIONSDIALOG_NOTIFICATION_LOAD = 0x1,
		AIMP_SERVICE_OPTIONSDIALOG_NOTIFICATION_LOCALIZATION = 0x2,
		AIMP_SERVICE_OPTIONSDIALOG_NOTIFICATION_SAVE = 0x3,
		AIMP_SERVICE_OPTIONSDIALOG_NOTIFICATION_CAN_SAVE = 0x4
	}
}